import { character } from "./Sprites";

export var movements = [
    { id: 0, x: -0.2, y: 0, start_anm: character.static, final_anm: character.static, duration: 0, delay: 2, scaleX: 1 },
    { id: 1, x: 0.35, y: 0, start_anm: character.walking, final_anm: character.talking, duration: 7, delay: 0, scaleX: 1, text: "hi!" },
    { id: 2, x: 0.35, y: 0, start_anm: character.talking, final_anm: character.talking, duration: 0, delay: 0, scaleX: 1, text: "welcome to the projects page" },
    { id: 3, x: 0.35, y: 0, start_anm: character.talking, final_anm: character.talking, duration: 0, delay: 0, scaleX: 1, text: "i'm <blank> and i'm going to guide you today" },
    { id: 4, x: 0.49, y: 0, start_anm: character.walking, final_anm: character.talking_pointing_br, duration: 3, delay: 0, scaleX: 1, text: "this is gizmo, he may appear a few times during the tour" },
    { id: 5, x: 0.47, y: 0, start_anm: character.walking, final_anm: character.static, duration: 1, delay: 0, scaleX: -1 },
    { id: 6, x: 0.47, y: 0, start_anm: character.talking, final_anm: character.static, duration: 0, delay: 0, scaleX: 1, text: "now, going to the first project" },
    { id: 7, x: 0.47, y: 0, start_anm: character.static, final_anm: character.changing, duration: 1, delay: 0, scaleX: 1, action: "nextSlide", action_time: 1300 },
    { id: 8, x: 0.47, y: 0, start_anm: character.static, final_anm: character.presenting, duration: 0, delay: 0, scaleX: 1 },
    { id: 9, x: 0.47, y: 0, start_anm: character.presenting, final_anm: character.presenting, duration: 0, delay: 0, scaleX: 1, text: "this is trevis forecast" },
    { id: 10, x: 0.8, y: 0, start_anm: character.walking, final_anm: character.talking, duration: 4, delay: 0, scaleX: 1, text: "trevis forecast is a course project done at senai by" },
    { id: 11, x: 0.8, y: 0, start_anm: character.talking, final_anm: character.talking, duration: 0, delay: 0, scaleX: 1, text: "luizblank in collaboration with eric coutinho using 2 external apis" },
    { id: 12, x: 0.8, y: 0, start_anm: character.talking, final_anm: character.talking, duration: 0, delay: 0, scaleX: 1, text: "VisualCrossingAPI - an API that obtains weather forecast information using coordinates" },
    { id: 13, x: 0.8, y: 0, start_anm: character.talking, final_anm: character.talking, duration: 0, delay: 0, scaleX: 1, text: "OpenCageAPI - an API that converts coordinates to places" },
    { id: 14, x: 0.8, y: 0, start_anm: character.static, final_anm: character.pressing_button, duration: 1, delay: 0, scaleX: 1, action: "setBackground2Status", action_time: 1600},
    { id: 15, x: 0.4, y: 0, start_anm: character.walking, final_anm: character.talking, duration: 4, delay: 0, scaleX: -1, text: "as you can see and as the name suggests" },
    { id: 16, x: 0.4, y: 0, start_anm: character.talking, final_anm: character.talking, duration: 0, delay: 0, scaleX: 1, text: "this is an weather forecasting website" },
    { id: 17, x: 0.4, y: 0, start_anm: character.talking, final_anm: character.talking, duration: 0, delay: 0, scaleX: 1, text: "it gets your current location and uses visual crossing to obtain" },
    { id: 18, x: 0.4, y: 0, start_anm: character.talking, final_anm: character.talking, duration: 0, delay: 0, scaleX: 1, text: "the weather forecast for your location" },
    { id: 19, x: 0.6, y: 0, start_anm: character.walking, final_anm: character.talking, duration: 3, delay: 0, scaleX: 1, text: "creating an account and logging in, gives you access to two new features" },
    { id: 20, x: 0.6, y: 0, start_anm: character.talking, final_anm: character.talking, duration: 0, delay: 0, scaleX: 1, text: "1. add new locations to your account by selecting them on the map" },
    { id: 21, x: 0.6, y: 0, start_anm: character.talking, final_anm: character.talking, duration: 0, delay: 0, scaleX: 1, text: "2. switching between them anytime you want" },
    { id: 22, x: 0.47, y: 0, start_anm: character.walking, final_anm: character.talking, duration: 2, delay: 0, scaleX: -1, text: "this was the first time they used external apis like this" },
    { id: 23, x: 0.47, y: 0, start_anm: character.talking, final_anm: character.talking, duration: 2, delay: 0, scaleX: 1, text: "which gave a great overview of what you can do with them" },
    { id: 24, x: 0.47, y: 0, start_anm: character.talking, final_anm: character.talking, duration: 2, delay: 0, scaleX: 1, text: "sometimes a two week project can teach you a lot" },
    { id: 25, x: 0.47, y: 0, start_anm: character.static, final_anm: character.static, duration: 2, delay: 0, scaleX: 1},
]